### ISSUE TITLE
Error on Import new subscriptions to group

### ISSUE THREAD

**Issue by TheCycoONE** [Heckie75/kodi-addon-podcast#13]
I don't really know what I'm doing with this addon but I was able to cause an error so:

What I did:
Install RSS Podcast
Register new account on gPodder.net
Go to addon settings and add credentials to the gPodder.net menu, Apply Changes
Go to Actions menu in addon settings
Select Import new subscriptions to group
Select any category
Observe box saying there was an error and to check logs.

Error in logs:
```
2021-07-25 10:21:07.947 T:1162  WARNING <general>: RunScript called for a non-script addon 'plugin.audio.podcasts'. This behaviour is deprecated.
2021-07-25 10:21:07.947 T:50559    INFO <general>: initializing python engine.
2021-07-25 10:21:12.023 T:50559   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/home/family/.kodi/addons/plugin.audio.podcasts/addon.py", line 734, in <module>
                                                       mediathek.import_gpodder_subscriptions("True" == sys.argv[2])
                                                     File "/home/family/.kodi/addons/plugin.audio.podcasts/addon.py", line 657, in import_gpodder_subscriptions
                                                       name, entries = self._parse_opml(
                                                     File "/home/family/.kodi/addons/plugin.audio.podcasts/addon.py", line 359, in _parse_opml
                                                       opml_data["opml"]["body"]["outline"])
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2021-07-25 10:21:12.051 T:50559    INFO <general>: Python interpreter stopped
```

**Comment by Heckie75** [comment]
Please do the following

1. Open gpodder.net and login with your username and password
2. Call the following URL (replace <username> with your username): https://www.gpodder.net/subscriptions/<username>.opml
3. Take a look at the source code, e.g. view-source:https://www.gpodder.net/subscriptions/<username>.opml

The file should look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <title>heckie's Subscription List</title>
    <dateCreated>Sun, 25 Jul 2021 15:52:04 +0000</dateCreated>
  </head>
  <body>
    <outline xmlUrl="https://www.heise.de/ct/uplink/ctuplinkvideohd.rss" description="Mitglieder der c't-Redaktion diskutieren über Themen aus dem Heft und was
sonst noch so in der IT-Welt passiert." type="rss" htmlUrl="https://www.heise.de/ct/" title="c't uplink" text="c't uplink"/>
    <outline xmlUrl="http://podcasts.files.bbci.co.uk/p016tl04.rss" description="Global business news, with live guests and contributions from Asia and the
USA." type="rss" htmlUrl="http://www.bbc.co.uk/programmes/p016tl04" title="Business Matters" text="Business Matters"/>
 ...
```

There must this hierarchie: ompl -> body --> outline (at least one outline element)

**Comment by TheCycoONE** [comment]
The error stopped happening after I added a subscription. It seems the plugin is just not handing the empty case.

**Comment by Heckie75** [comment]
Fine, error handling will probably be better with one of the coming versions. You can already download the version 2.1.1 from Github. 

I am going to close this issue. 

Thanks!
