### ISSUE TITLE
The RSS podcasts addon crashes immediately after starting it

### ISSUE THREAD

**Issue by ErikBrown2** [Heckie75/kodi-addon-podcast#23]
Is this addon still supported? It crashes immediately after starting it. This is the same on all my Kodi setups. I have tried the official release 2.3.0 and also 2.3.1.

**Comment by Heckie75** [comment]
Yes, it is supported and problems are not known. Maybe take a look at Kodi.log

**Comment by Heckie75** [comment]
I have seen an error on an other device,i.e. 
```
2024-01-21 10:10:50.769 T:11064   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "D:\PortableApps\KodiPortable\App\Kodi\portable_data\addons\plugin.audio.podcasts\addon.py", line 9, in <module>
                                                       from resources.lib.podcasts.actions.search_fyyd_action import SearchFyydAction
                                                     File "D:\PortableApps\KodiPortable\App\Kodi\portable_data\addons\plugin.audio.podcasts\resources\lib\podcasts\actions\search_fyyd_action.py", line 3, in <module>
                                                       from resources.lib.podcasts.actions.remote_action import RemoteAction
                                                     File "D:\PortableApps\KodiPortable\App\Kodi\portable_data\addons\plugin.audio.podcasts\resources\lib\podcasts\actions\remote_action.py", line 6, in <module>
                                                       class RemoteAction(OpmlAction):
                                                     File "D:\PortableApps\KodiPortable\App\Kodi\portable_data\addons\plugin.audio.podcasts\resources\lib\podcasts\actions\remote_action.py", line 11, in RemoteAction
                                                       def subscribe_feeds(self, feeds: list[dict]) -> 'tuple[list[dict], bool]':
                                                   TypeError: 'type' object is not subscriptable
                                                   -->End of Python script error report<--
```

Maybe this is what you have also seen. I'm going to investigate what the problem is.

**Comment by Heckie75** [comment]
I guess it's related to the python interpreter that maybe comes with Kodi's Windows installation. I'm going to fix this and provide a new version.

**Comment by ErikBrown2** [comment]
Thanks for your quick response. It gives me hope that this great addon will be working soon again. You can find my Kodi log here  https://paste.kodi.tv/ewaricipil
I know it is an older version of Kodi but if you require, then I can also upload the log from another PC with the current version of Kodi. Before I uploaded the log, I started RSS Podcasts and it did not start but I got the message "RSS Podcasts error, Check the log for more information." on the right bottom of the screen. If you want me to test anything, then please let me know.

**Comment by Heckie75** [comment]
@ErikBrown2 This is exactly the error that I've fixed this morning. At this moment it is in review and will be available soon, see https://github.com/xbmc/repo-plugins/pull/4451

**Comment by ErikBrown2** [comment]
Thank you very much!! I installed te new version of the addon and it works again. Really great!
