### ISSUE TITLE
HTTP Client Does Not Follow Redirects

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#3]
A few of my podcast feeds do not open in Kodi and result in an error. However, they do open properly in gPodder (Desktop) and AntennaPod (Android) while using the same OPML file. The error is pasted from the kodi.log below

```

2021-04-27 16:26:39.801 T:4582    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.parsers.expat.ExpatError'>
                                                   Error Contents: mismatched tag: line 6, column 2
                                                   Traceback (most recent call last):
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 331, in <module>
                                                       mediathek.handle(sys.argv)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 320, in handle
                                                       getattr(self, url_params["call"][0])(parent=node,
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 183, in renderRss
                                                       items, image = self._load_rss_feed(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 151, in _load_rss_feed
                                                       rss_feed = self._loadRss(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 147, in _loadRss
                                                       return xmltodict.parse(_data)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/xmltodict.py", line 330, in parse
                                                       parser.Parse(xml_input, True)
                                                   xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2
                                                   -->End of Python script error report<--
```

To investigate the issue, I compared the RSS URLs of the podcasts that work to the RSS URLs that do not work. It appears that a few of the RSS URLs redirect to another URL. I confirmed this by using the Network Monitor feature of Firefox web browser on my desktop PC. Some podcasters do not store the RSS XML file directly on their website; the URL that they provide redirects to a third party hosting provider which contains the XML file. That way they can change providers without changing the URL.

The URLs that redirect return HTTP status code 301 (Moved Permanently). The addon expects to receive an XML file in the HTTP response, and when it attempts to parse the body of a 301 response it results in an error.

I added 2 log statements to the code in the _requestHttp method to print the HTTP response status, and the redirected URL if the code is 301 for debugging purposes.
 
<pre>
        res = conn.getresponse()
        data = res.read()
        <b>xbmc.log(msg=f"HTTP Response Status: {res.status} {res.reason}", level=xbmc.LOGINFO)
        if res.status == 301:
            xbmc.log(msg=f"HTTP Redirect URL: {res.getheader('Location')}", level=xbmc.LOGINFO)</b>
</pre>
This resulted in the following log when attempting to load a podcast URL that redirects

<pre>
<b>2021-04-27 16:26:39.793 T:4582     INFO <general>: HTTP Response Status: 301 Moved Permanently
2021-04-27 16:26:39.793 T:4582     INFO <general>: HTTP Redirect URL: http://thedickshow.libsyn.com/rss</b>
2021-04-27 16:26:39.801 T:4582    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.parsers.expat.ExpatError'>
                                                   Error Contents: mismatched tag: line 6, column 2
                                                   Traceback (most recent call last):
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 331, in <module>
                                                       mediathek.handle(sys.argv)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 320, in handle
                                                       getattr(self, url_params["call"][0])(parent=node,
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 183, in renderRss
                                                       items, image = self._load_rss_feed(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 151, in _load_rss_feed
                                                       rss_feed = self._loadRss(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 147, in _loadRss
                                                       return xmltodict.parse(_data)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/xmltodict.py", line 330, in parse
                                                       parser.Parse(xml_input, True)
                                                   xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2
                                                   -->End of Python script error report<--
</pre>

To fix the issue, I propose the code logic should be something like:

1. When the HTTP response is received, check the status code before attempting to parse
2. If the status code is 301, get the redirect URL from the response header and send another request to the redirect URL
3. Parse the response body when the response status code is 200

To reproduce the issue, you may use the URL [https://thedickshow.com/feed/podcast/](https://thedickshow.com/feed/podcast/) in your OPML file. This is the RSS URL given on the podcaster's website. Based on the Firefox Network Monitor activity, I can see that it actually redirects twice. It first redirects to [http://thedickshow.libsyn.com/rss](http://thedickshow.libsyn.com/rss), which then redirects to [http://thedickshow.libsyn.com/thedickshow](http://thedickshow.libsyn.com/thedickshow), which contains the actual XML file. So, in this case a total of 3 HTTP requests would be necessary to load the podcast feed.

**Comment by Heckie75** [comment]
Please check latest release.

```
2021-04-28 16:42:13.060 T:175042    INFO <general>: Podcast moved permanently from https://thedickshow.com/feed/podcast to http://thedickshow.libsyn.com/rss
2021-04-28 16:42:13.332 T:175042    INFO <general>: Podcast moved permanently from http://thedickshow.libsyn.com/rss to http://thedickshow.libsyn.com/thedickshow
2021-04-28 16:42:13.583 T:175042    INFO <general>: Podcast moved permanently from http://thedickshow.libsyn.com/thedickshow to https://thedickshow.libsyn.com/thedickshow
```

PS: What the hell is the d**k show?

**Comment by stobb3s** [comment]
> PS: What the hell is the d**k show?

Haha. The host of the podcast is nicknamed "Dick", and the podcast is named after him. It's an odd name, but I suggested it because that URL redirects multiple times to help you test the fix.

Anyway, I updated the code and it works perfectly now. All of my podcast feeds open and play correctly. I am closing the issue.

**Comment by stobb3s** [comment]
By the way, you should consider submitting this add-on to the official Kodi 19 add-on repository. I'm sure you are aware that the add-on compatibility for Kodi 19 is currently quite poor. For Kodi 18 and earlier, there were 2 official add-ons for listening to podcasts: [Apple iTunes Podcasts](https://github.com/dersphere/plugin.video.itunes_podcasts) and [AudioPodcatcher](https://github.com/raptor2101/PodCatcher). Apple iTunes Podcasts has been abandoned for many years, and the maintainer of AudioPodcatcher said that he won't port it to python3 for Matrix compatibility. This means that there is currently no plan for any official podcast support for Kodi 19.

As far as I'm aware, your add-on is the only way to listen to podcasts on Kodi 19 - official or unofficial. It's unfortunate that such a major feature is lacking official support in the current version of Kodi. Surely, this is preventing some people from upgrading to Matrix. I used AudioPodcatcher in Kodi 18, but your add-on is much better in my opinion. I think the community would greatly appreciate if you made this add-on available in the official Kodi 19 repo.
