### ISSUE TITLE
Error Decoding HTTP Response

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#6]
For the latest version 2.0.3, there is an error when receiving an encoded http response other than UTF-8. Error is pasted below.
```
2021-05-17 22:38:47.255 T:9873    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'utf-8' codec can't decode byte 0xe2 in position 225015: invalid continuation byte
                                                   Traceback (most recent call last):
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 591, in <module>
                                                       mediathek.handle(sys.argv)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 438, in handle
                                                       self._render_rss(path, url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 281, in _render_rss
                                                       title, description, image, items = self._load_rss(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 238, in _load_rss
                                                       res, cookies = self._http_request(url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 187, in _http_request
                                                       text = res.text.encode(res.encoding).decode("utf-8")
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 225015: invalid continuation byte
                                                   -->End of Python script error report<--
```
Looks like the new code on line 187 is causing it. The podcast RSS file is encoded in ISO-8859-1, and attempting to decode it using UTF-8 results in an error. I changed the line to below and it fixed the issue for me:
```
text = res.text.encode(res.encoding).decode(res.encoding)
```
You can reproduce the issue by using this URL [http://feeds.feedburner.com/BaseballHqRadio](http://feeds.feedburner.com/BaseballHqRadio)

**Comment by Heckie75** [comment]
@stobb3s 

I have fixed this in 2.0.3-pre2.

Pls. check if it works for you.
